name: Build and Publish Latest Release

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Prepare artifacts
        run: |
          mkdir artifact
          cp dist/index.html artifact/iso20022-mig-editor.html
          mkdir pages
          cp dist/index.html pages/
          cp dist/manifest.json pages/
          cp dist/sw.js pages/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      - name: Delete existing 'latest' release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: latest
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest
          draft: false
          prerelease: false
          files: artifact/iso20022-mig-editor.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
